### PR TITLE
Fix handling of topics with periods

### LINKED ISSUE #45: Topics with periods should be supported.
Working with a customer who discovered. 

org.group.data.xxxx should be supported.

> Kafka topic naming. If you name a topic with periods for namespacing (I.e. org.group.data), the HDFS connector doesn’t like it. (https://github.com/confluentinc/kafka-connect-hdfs/blob/5b563417ce06c93c24c85b42d0cc94504aabe69e/src/main/java/io/confluent/connect/hdfs/filter/TopicPartitionCommittedFileFilter.java) Instead of assuming the second item in the array on line 37 is the partition, use the last item in the array; that might fix it.

### PR DESCRIPTION
**Pull request by jingw**
Currently the filters / offset extraction rely on splitting on dot. If there's a topic called `namespace.topic`, it'll extract `namespace` and compare that with the topic name. This breaks recovery, where it looks for the max offset.

Also fixed typo in HdfsSinkConnecorConstants and deleted unused CommittedFileWithEndOffsetFilter.

Closes #45

### CODE REVIEW

**Comment by jingw** [comment]
Our legal folks filled out the CLA. Please let me know if I still need to do something for that.

File: src/main/java/io/confluent/connect/hdfs/FileUtils.java [hunk 1]
```diff
@@ -151,7 +152,12 @@ public static FileStatus fileStatusWithMaxOffset(Storage storage, Path path,
   }
 
   public static long extractOffset(String filename) {
-    return Long.parseLong(filename.split(HdfsSinkConnecorConstants.COMMMITTED_FILENAME_SEPARATOR_REGEX)[3]);
+    Matcher m = HdfsSinkConnectorConstants.COMMITTED_FILENAME_PATTERN.matcher(filename);
+    // NB: if statement has side effect of enabling group() call
+    if (!m.matches()) {
+      throw new IllegalArgumentException(filename + " does not match COMMITTED_FILENAME_PATTERN");
+    }
+    return Long.parseLong(m.group(4));
```
Comment (ewencp) [inline src/main/java/io/confluent/connect/hdfs/FileUtils.java]: Should we maybe change this to a named constant in `HdfsSinkConnectorConstants` since it could change if, e.g. any grouping was adjusted in `COMMITTED_FILENAME_PATTERN`?

File: src/main/java/io/confluent/connect/hdfs/filter/TopicCommittedFileFilter.java [hunk 2]
```diff
@@ -31,8 +33,12 @@ public boolean accept(Path path) {
...
     }
     String filename = path.getName();
-    String[] parts = filename.split(HdfsSinkConnecorConstants.COMMMITTED_FILENAME_SEPARATOR_REGEX);
-    String topic = parts[0];
+    Matcher m = HdfsSinkConnectorConstants.COMMITTED_FILENAME_PATTERN.matcher(filename);
+    // NB: if statement has side effect of enabling group() call
+    if (!m.matches()) {
+      throw new AssertionError("match expected because of CommittedFileFilter");
+    }
+    String topic = m.group(1);
```
Comment (ewencp) [inline src/main/java/io/confluent/connect/hdfs/filter/TopicCommittedFileFilter.java]: Same re: this magic constant and moving it to `HdfsSinkConnectorConstants`.

File: src/main/java/io/confluent/connect/hdfs/filter/TopicPartitionCommittedFileFilter.java [hunk 3]
```diff
@@ -32,9 +34,13 @@ public boolean accept(Path path) {
...
     String filename = path.getName();
-    String[] parts = filename.split(HdfsSinkConnecorConstants.COMMMITTED_FILENAME_SEPARATOR_REGEX);
-    String topic = parts[0];
-    int partition = Integer.parseInt(parts[1]);
+    Matcher m = HdfsSinkConnectorConstants.COMMITTED_FILENAME_PATTERN.matcher(filename);
+    // NB: if statement has side effect of enabling group() call
+    if (!m.matches()) {
+      throw new AssertionError("match expected because of CommittedFileFilter");
+    }
+    String topic = m.group(1);
```
Comment (ewencp) [inline src/main/java/io/confluent/connect/hdfs/filter/TopicPartitionCommittedFileFilter.java]: And a couple more constants that could be named.

File: src/test/java/io/confluent/connect/hdfs/filter/CommittedFileFilterTest.java [hunk 4]
```diff
@@ -88,6 +90,13 @@ public void testTopicPartitionCommittedFileFilter() throws Exception {
     assertTrue(files.contains(valid1.getName()));
     assertTrue(files.contains(valid2.getName()));
 
+    FileStatus[] statusesOtherTopic = fs.listStatus(
+            ROOT_PATH, new TopicCommittedFileFilter("namespace.topic"));
+    assertEquals(1, statusesOtherTopic.length);
+    assertEquals(validOtherTopic.getName(), statusesOtherTopic[0].getPath().getName());
+
+    fs.deleteOnExit(ROOT_PATH);
```
Comment (ewencp) [inline src/test/java/io/confluent/connect/hdfs/filter/CommittedFileFilterTest.java]: Seems this line is accidentally duplicated?

**Comment by ewencp** [comment]
@jingw Looks great. I left a couple of comments about cleanup and duplicated code in a test, but should all be trivial to cleanup and get committed.

**Comment by ewencp** [comment]
test this please

**Comment by jingw** [comment]
I made the suggested cleanups. Let me know if you need anything else. Thanks!

**Comment by ewencp** [comment]
ok to test

**Comment by ewencp** [comment]
LGTM, thanks for the contribution!

**Comment by blbradley** [comment]
Did this make it into 3.0.1? I have a topic like `okcoin.streaming.btcusd.trades` and I get this traceback upon recovery:

```
[2016-09-09 14:36:25,225] ERROR Task cryptocoin-hdfs-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.NumberFormatException: For input string: "streaming"
       	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
       	at java.lang.Integer.parseInt(Integer.java:580)
       	at java.lang.Integer.parseInt(Integer.java:615)
       	at io.confluent.connect.hdfs.filter.TopicPartitionCommittedFileFilter.accept(TopicPartitionCommittedFileFilter.java:37)
       	at io.confluent.connect.hdfs.FileUtils.fileStatusWithMaxOffset(FileUtils.java:141)
       	at io.confluent.connect.hdfs.FileUtils.fileStatusWithMaxOffset(FileUtils.java:130)
       	at io.confluent.connect.hdfs.TopicPartitionWriter.readOffset(TopicPartitionWriter.java:390)
       	at io.confluent.connect.hdfs.TopicPartitionWriter.resetOffsets(TopicPartitionWriter.java:453)
       	at io.confluent.connect.hdfs.TopicPartitionWriter.recover(TopicPartitionWriter.java:203)
       	at io.confluent.connect.hdfs.DataWriter.recover(DataWriter.java:239)
       	at io.confluent.connect.hdfs.DataWriter.open(DataWriter.java:281)
       	at io.confluent.connect.hdfs.HdfsSinkTask.open(HdfsSinkTask.java:104)
       	at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:428)
       	at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1000(WorkerSinkTask.java:54)
       	at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:464)
       	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:234)
       	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$2.onSuccess(AbstractCoordinator.java:255)
       	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$2.onSuccess(AbstractCoordinator.java:250)
       	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:133)
       	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:107)
       	at org.apache.kafka.clients.consumer.internals.RequestFuture$2.onSuccess(RequestFuture.java:182)
       	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:133)
       	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:107)
       	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$SyncGroupResponseHandler.handle(AbstractCoordinator.java:459)
       	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$SyncGroupResponseHandler.handle(AbstractCoordinator.java:445)
       	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:702)
       	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:681)
       	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:167)
       	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:133)
       	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:107)
       	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.onComplete(ConsumerNetworkClient.java:426)
       	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:278)
       	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:360)
       	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
       	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:192)
       	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:163)
       	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:266)
       	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.ensurePartitionAssignment(ConsumerCoordinator.java:366)
       	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:975)
       	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:938)
       	at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:316)
       	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:222)
       	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
       	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
       	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
       	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
       	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)
```

**Comment by blbradley** [comment]
It did not. See you at the next release!

**Comment by blbradley** [comment]
I put an image (from automated build) on [Docker Hub](https://hub.docker.com/r/coinsmith/cp-kafka-connect-hdfs) from the 3.0.1 images that has a custom build with this patch applied in case anyone needs this fix.
